### ISSUE TITLE
March speaker - which talk?

### ISSUE THREAD

**Issue by garethellis36** [phpoxford/ideas#7]
I have arranged for Michael Cullum (@MichaelCullumUK on Twitter, MichaelC on IRC) to speak at our March meet-up. He has sent me [this link to his current talk titles](https://www.dropbox.com/s/09wz9c1n26novl1/talks.png?dl=0). 

What would people like to see being spoken about? I note there are a few beginner-level talks which may not be suited to the regulars, but perhaps this would be a good way to attract some newcomers.

**Comment by ascii-soup** [comment]
I don't mind. AI talk could be interesting.

**Comment by martindilling** [comment]
I'd like to learn more about AI too _(hint: spires)_

**Comment by mcidahechi** [comment]
I'm easy. I think I'd probably learn more new stuff from the AI one. How that would translate to being useful as a PHP dev (i.e. will I ever use it) will remain to be seen!

**Comment by liquorvicar** [comment]
+1 for the AI talk

**Comment by garethellis36** [comment]
<MichaelC> Would you mind going for another one of my talks? My neuroscience one is going to require a lot of prep (40+ hours) which I'd rather only do for a conference and I won't have time to do that before the end of this month anyway

**Comment by ascii-soup** [comment]
In that case I have no preference.

**Comment by mcidahechi** [comment]
MichealC: At this stage I'd kind of prefer one I've done before... As there's not long to go:
- How we Build phpBB: TNG;
- phpBB, Meet Symfony
- Converting a website to a new religion: Symfony

**Comment by mcidahechi** [comment]
+1 for How We Build phpBB: the next generation. +10 if patrick stewart is involved.
